version:  '3.3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - '.:/app'
    environment:
      - 'COMPOSER_HOME=/tmp/composer'
      - 'COMPOSER_ALLOW_SUPERUSER=1'
      - 'XDEBUG_MODE=develop,debug'



